services:
  raceops:
    # We use a fixed image name that matches your GitHub repo path
    image: ghcr.io/eisendev/raceops:latest
    container_name: raceops
    ports:
      - "3000:3000"
    # This tells Docker to load variables from the .env file I created on your server
    env_file:
      - .env
    restart: always
