services:
  raceops:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/raceops:latest
    container_name: raceops
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - IRON_SESSION_PASSWORD=${IRON_SESSION_PASSWORD}
      - NODE_ENV=production
    restart: always
